[package]
name = "solink"
version = "0.2.0"
edition = "2021"

[dependencies]
byteordered = "0.6.0"
clap = { version = "4.5.1", features = ["derive"] }
indexmap = "2.2.5"
num_enum = { version = "0.7.2", features = ["complex-expressions"] }
